Cord 108
ProtocolONE/chihaya pull request #2
Opened 2019-04-04 20:58 UTC by Clipeus

2019-04-09 08:26 UTC, misterion requested changes

2019-04-09 08:26 UTC, misterion commented on frontend/cord/core/core.go
> +// InitCord ...
Зачем это? Зачем выключать линтер так? Уберите эти не нудные док блоки

2019-04-09 08:26 UTC, misterion commented on frontend/cord/database/database.go
> +var memTorrentManager = &MemTorrentManager{}
Зачем объявление глобальной переменной тут?

2019-04-09 08:26 UTC, misterion commented on frontend/cord/models/models.go
> +	// ErrorInvalidJSONFormat ...
Это терроризм какой-то. Зачем это? Вы что это руками делали??????

2019-04-09 08:26 UTC, misterion commented on geo/geo.go
> +	lastBytes := (8*16 - ones) / 8
Серьезно? https://stackoverflow.com/questions/19882961/go-golang-check-ip-address-in-range

2019-04-09 08:57 UTC, misterion requested changes

2019-04-09 08:57 UTC, misterion commented on geo/geo.go
> +		vals, err = client.ZRevRangeByLex(keyV6, redis.ZRangeBy{
Получайте данные о положении напрямую из базы maxmind  - она не должна жить в редисе.

2019-04-09 08:57 UTC, misterion commented on geo/geo.go
> +		IPv4ID = iPv4ToScore(ip, false)
Уберите это. В качестве ключей - байтовое предстапвление ip адреса

2019-04-09 08:57 UTC, misterion commented on frontend/cord/core/authentication/jwt_backend.go
> +// GenerateToken ...
Что это за глупости с комментариями заглушками? Объясните зачем вы это сделали?

2019-04-09 08:57 UTC, misterion commented on cmd/chihaya/main.go
>  	cord_hook.Init()
Почему не вы не используте штатные прехуки?

2019-04-09 08:57 UTC, misterion commented on example_config.yaml
> +    key_ipv6: "ipv6_location"
Удилить ipv6 с концами как я вам уже говорил ранее

2019-04-09 08:57 UTC, misterion commented on geo/geo.go
> +	Host        string `yaml:"host"`
Не нужно разделять адрес редиса на хост и порт - это строка Address

2019-04-09 08:57 UTC, misterion commented on geo/geo.go
> +	Password    string `yaml:"password"`
не нужно кастомизировать имя базы

2019-04-09 08:57 UTC, misterion commented on geo/geo.go
> +		DB:       config.DB,
Не нудно указывать базу!!!! Это deprecated уже более 2 лет!!!

2019-04-09 08:57 UTC, misterion commented on geo/geo.go
> +
Вся реализация этого метода не верная. Вы должны использовать maxmind db для работы с позицией

2019-04-09 09:17 UTC, Clipeus commented on frontend/cord/core/authentication/jwt_backend.go
> +// GenerateToken ...
Этот код был взять из другого нашего проекта. Точно такой же код авторизации в стуле. Для чего щас уже не помню.

2019-04-09 09:18 UTC, Clipeus commented on cmd/chihaya/main.go
>  	cord_hook.Init()
ну это и есть штатный, то есть зарегистрированный наш новый хук, который прописан в конфиге

2019-04-09 09:19 UTC, Clipeus commented on example_config.yaml
> +    key_ipv6: "ipv6_location"
IPv6 не нужно поддерживать?

2019-04-09 11:47 UTC, Clipeus commented on frontend/cord/core/core.go
> +// InitCord ...
Как я написал включил что бы на тревисе строилось, да и раздражает меня когда все это зеленым подчеркивается и куча варингов.

2019-04-09 11:47 UTC, Clipeus commented on frontend/cord/database/database.go
> +var memTorrentManager = &MemTorrentManager{}
убрал

2019-04-09 11:48 UTC, Clipeus commented on frontend/cord/models/models.go
> +	// ErrorInvalidJSONFormat ...
Нет, для этого есть хороший тул, копи-паст называется.

2019-04-09 11:48 UTC, Clipeus commented on geo/geo.go
> +	lastBytes := (8*16 - ones) / 8
убрал

2019-04-09 11:48 UTC, Clipeus commented on geo/geo.go
> +		vals, err = client.ZRevRangeByLex(keyV6, redis.ZRangeBy{
убрал

2019-04-09 11:48 UTC, Clipeus commented on geo/geo.go
> +		IPv4ID = iPv4ToScore(ip, false)
убрал

2019-04-09 11:48 UTC, Clipeus commented on geo/geo.go
> +	Host        string `yaml:"host"`
исправил

2019-04-09 11:49 UTC, Clipeus commented on geo/geo.go
> +	Password    string `yaml:"password"`
исправил

2019-04-09 11:49 UTC, Clipeus commented on geo/geo.go
> +		DB:       config.DB,
исправил

2019-04-09 11:49 UTC, Clipeus commented on geo/geo.go
> +
переделал

2019-04-12 09:45 UTC, misterion requested changes

2019-04-12 09:45 UTC, misterion commented on example_config.yaml
> +    database: "D:\Projects\Syncopate\sources\ProtocolONE\chihaya\geo\data\GeoLite2-City.mmdb"
Что-то тут написано совсем не то, что должно - зачем тут ваш локальный пусть вместо относительного в рамках этого проекта?

2019-04-12 09:45 UTC, misterion commented on frontend/cord/core/authentication/jwt_backend.go
> +// GenerateToken ...
Уберите их - что за глупости

2019-04-12 09:45 UTC, misterion commented on frontend/cord/core/core.go
> +// InitCord ...
Вы сделали глупое - просто заткнули линтер дыркой. раздражает правило? выклдючите локально или пишите нормальные, имебщие смысл и ценность doc blocks

2019-04-12 09:45 UTC, misterion commented on geo/geo.go
> +		DB:       0,
Не нужно указывать DB вообще. Достаочно только Addr и Password

2019-04-12 09:45 UTC, misterion commented on geo/geo.go
> +func selectIPByRadius(client *Client, targetIP string, IPs []string) ([]string, error) {
Тут написана какая-то глупость. Что должно было быть вместо: 
1. Каждый новый приходящий на трекер клиент за анонсом добавляется в редис в список пиров где в качестве ключа выступает peer id а в качестве значения ширина и долгота полученная из IP адреса. В  качестве ключа для запиши гео информации выступает идентификатор торрента (hash).
2. Должен быть изменен процесс подбора пиров на отдачу во время запроса анонса: 
- получить  ширину и долгту текущего клиента 
- запросить из ключа в редисе (hash торрента) список пиров с учетом радиуса
- использовать список для пересечеия и фильтрации с другими правилами

Что написали вы:  какую-то дичь. Во время фильтрации пиров в peer_store.go вы добавляете пир в релис, пытается пересечь его там и тут же удаляете ключи. Судя по всему, Михаил, вы не понимате, что вам нужно сделать и что вы делаете.

2019-04-12 15:31 UTC, Clipeus commented on example_config.yaml
> +    database: "D:\Projects\Syncopate\sources\ProtocolONE\chihaya\geo\data\GeoLite2-City.mmdb"
А что не так, себе для тестирования вписал свой путь. Для запуска в продакш есть свой конфиг, там можно какой нравится путь указать. Если это конфиг мешает могу его с гита удалить.

2019-04-17 06:29 UTC, misterion requested changes

2019-04-17 06:29 UTC, misterion commented on example_config.yaml
> +    database: "D:\\Projects\\Syncopate\\sources\\ProtocolONE\\chihaya\\geo\\data\\GeoLite2-City.mmdb"
Уберите локальный путь! Используйте относительный путь!

2019-04-17 06:29 UTC, misterion commented on geo/geo.go
> +		zap.S().Warnw("Cannot open geoip2 data file", zap.String("error", err.Error()))
Это не warn - это fatal. Если гео базу открыть не смогли мы не долдны работать.

2019-04-17 06:29 UTC, misterion commented on storage/memory/peer_store.go
> +			canAdd = !(useGeo != canAdd)
давайте это условие по человечески перепишем

2019-04-17 10:50 UTC, misterion approved these changes

2019-04-17 11:09 UTC, merged