Cord 107
ProtocolONE/chihaya pull request #3
Opened 2019-04-22 16:01 UTC by Clipeus

2019-04-23 06:44 UTC, misterion requested changes

2019-04-23 06:44 UTC, misterion commented on middleware/cord/stat/stat.go
> +	field := fmt.Sprintf("%s.%d", si.infoHash, si.connId)
Запрос выполняется вне транзакции - это может привексти к тому что данные будет между 2 ключами не консистентны.

2019-04-23 06:44 UTC, misterion commented on middleware/cord/stat/stat.go
> +	redisConn := h.redisPool.Get()
Это очень странно открывать коннект на каждый запрос - на месте редис сервера я бы очень расстроился и перестал вам отвечать так быстро как это делается при постоянно открытом (одном) соединении. Расстроился я бы потому, что редис - однопоточный сервер и больше чем вы из него выжмеете по 1 конекту от 1 сервиса не получится.

2019-04-23 06:44 UTC, misterion commented on middleware/cord/stat/stat.go
> +	si.userId = req.Peer.ID.String()
Давайте пожалуйста проверим, что лежит в Peer.ID и что лежит в текущем сервере? В ГН там передавался UserID платформы ГН и мы строили статистику по пользователяем, а не по идентификаторам самого торрент трекера. Что тут?

2019-04-23 06:44 UTC, misterion commented on cmd/chihaya/main.go
>  	"github.com/ProtocolONE/chihaya/geo"
В реквесте не вижу всей части про пересчет статистики из реквемст №3 и №8 опентрекера. Их тут кажется еще нет.

2019-04-23 07:13 UTC, Clipeus commented on middleware/cord/stat/stat.go
> +	redisConn := h.redisPool.Get()
Сам чихай так делает, на каждом анонсе. Но тут все же не коннект идет, а берется коннект из пула.

2019-04-23 07:17 UTC, Clipeus commented on middleware/cord/stat/stat.go
> +	si.userId = req.Peer.ID.String()
То есть надо передавать в запросе наш UserID? Но пока нашего торрент клиента нет, то UserID и не передается. А PeerID не заменит UserID?

peer_id: urlencoded 20-byte string used as a unique ID for the client, generated by the client at startup. This is allowed to be any value, and may be binary data. There are currently no guidelines for generating this peer ID. However, one may rightly presume that it must at least be unique for your local machine, thus should probably incorporate things like process ID and perhaps a timestamp recorded at startup. See peer_id below for common client encodings of this field.

2019-04-23 07:19 UTC, Clipeus commented on cmd/chihaya/main.go
>  	"github.com/ProtocolONE/chihaya/geo"
то есть положить файлы merge_data.lua и merge_data.php?

2019-04-23 07:20 UTC, misterion commented on middleware/cord/stat/stat.go
> +	redisConn := h.redisPool.Get()
ок

2019-04-23 07:21 UTC, misterion commented on middleware/cord/stat/stat.go
> +	si.userId = req.Peer.ID.String()
А наш торрекнт клиент есть, он никуда пока не подевался - он от корда. И конечно пир ID и userID совершенно разные вещи.

2019-04-23 07:22 UTC, misterion commented on cmd/chihaya/main.go
>  	"github.com/ProtocolONE/chihaya/geo"
Ну не PHP =) отдельное приложение сюда рядышком или команда в чиче или запуск по таймеру в чиче

2019-04-24 14:58 UTC, Clipeus commented on middleware/cord/stat/stat.go
> +	si.userId = req.Peer.ID.String()
Добавил наш UserID

2019-04-25 06:15 UTC, misterion commented on frontend/udp/parser.go
> +			userHash = getReqValue(reqStr, "hash")
что-то тут не зватает. а как хеш валидируется?

2019-04-25 08:31 UTC, Clipeus commented on frontend/udp/parser.go
> +			userHash = getReqValue(reqStr, "hash")
Добавил валидацию

2019-04-26 05:23 UTC, misterion approved these changes
Отлично! Нужно тестировать!

2019-04-26 06:01 UTC, merged